-- 우리집 보드: "범용 서비스" 전환 마이그레이션 (그룹/방 단위 데이터 격리)
-- Supabase 대시보드 → SQL Editor 에 붙여넣고 한 번 실행하세요.
-- 안전 설계: 모두 'if not exists' / 기본값으로, 기존 2인용 데이터는 'default' 그룹으로 그대로 유지됩니다.

-- 1) 그룹(방) 테이블 ---------------------------------------------------------
create table if not exists public.groups (
  code       text primary key,                 -- 6자리 초대 코드 (예: ABC123)
  name       text not null default '우리집',    -- 그룹 이름
  members    text[] not null default '{}',      -- 멤버 이름 목록
  created_at timestamptz not null default now()
);

-- 로그인 없이 publishable(anon) 키로만 쓰므로, anon 이 그룹을 만들고/조회/참여할 수 있게 허용.
alter table public.groups enable row level security;
drop policy if exists "anon manage groups" on public.groups;
create policy "anon manage groups"
  on public.groups for all to anon
  using (true) with check (true);

-- 2) requests 테이블에 group_code 추가 ---------------------------------------
-- (requests 테이블은 앱 초기부터 존재. 없으면 아래 create 가 만든다.)
create table if not exists public.requests (
  id         bigint generated by default as identity primary key,
  item       text not null,
  requester  text,
  status     text not null default '필요해요',
  assignee   text,
  deadline   date,
  created_at timestamptz not null default now()
);

alter table public.requests
  add column if not exists group_code text not null default 'default';

create index if not exists requests_group_code_idx on public.requests (group_code);

-- 기존 데이터는 자동으로 'default' 그룹에 속함 (위 기본값). 명시적으로도 한 번 정리:
update public.requests set group_code = 'default' where group_code is null;

alter table public.requests enable row level security;
drop policy if exists "anon manage requests" on public.requests;
create policy "anon manage requests"
  on public.requests for all to anon
  using (true) with check (true);

-- 3) push_subscriptions 에 group_code 추가 -----------------------------------
alter table public.push_subscriptions
  add column if not exists group_code text not null default 'default';

create index if not exists push_subs_group_code_idx on public.push_subscriptions (group_code);

-- 4) 기존 2인용 'default' 그룹 시드 (있으면 건너뜀) ---------------------------
insert into public.groups (code, name, members)
values ('default', '우리집', array['와이프', '남편'])
on conflict (code) do nothing;

-- 5) 실시간(Realtime) 활성화 (이미 켜져 있으면 무시) ---------------------------
-- 대시보드 Database → Replication 에서 requests 가 켜져 있어야 실시간 동기화가 됩니다.
-- (SQL 로도 가능):  alter publication supabase_realtime add table public.requests;
